[package]
name = "nukrypt"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
libaes = "0.6.2"
litcrypt = "0.2"
structopt = "0.3.14"
reqwest = {version = "0.11", features = ["blocking"]}

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = 'abort'